import { scoreSourcedOffer } from "./sourced-scanner.mjs";

export function renderSourcedIntake({ date, offers, summary, config = {} }) {
  const lines = [
    `# Sourced Intake - ${date}`,
    "",
    "Generated by `npm run scan:sourced -- --intake`.",
    "",
    "Rules:",
    "- Run the BODY-READ GATE before tailoring or applying.",
    "- Fit is a scanner rule score from ATS metadata/body when available; the human BODY-READ GATE still overrides it.",
    "- Do not move a row into `tracker.html` until the posting is KEEP and comp clears.",
    "- If the posting is closed, delete/ignore the intake row and do not tailor.",
    "- `possible-duplicate` means same company/role family appeared elsewhere; verify req id before skipping.",
    "",
    "Summary:",
    `- Scanned: ${summary.scanned}`,
    `- New after filters/dedupe: ${summary.new}`,
    `- Filtered by title: ${summary.filteredTitle}`,
    `- Filtered by location: ${summary.filteredLocation}`,
    `- Hard duplicates: ${summary.duplicates}`,
    "",
    "| Status | Fit | Rule Signals | Company | Role | Location | Source | Flags |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
  ];

  for (const offer of offers) {
    const rating = offer.score == null || !offer.fit ? scoreSourcedOffer(offer, config) : offer;
    const flags = [
      rating.gate && rating.gate !== "review" ? rating.gate : "",
      ...(Array.isArray(rating.ruleFlags) ? rating.ruleFlags : []),
      offer.possibleDuplicate ? "possible-duplicate" : "",
      offer.reqId || "",
    ]
      .filter(Boolean)
      .join(", ");
    lines.push(
      [
        "[ ] gate",
        escapeCell(formatFit(rating)),
        escapeCell(rating.ratingReason || "-"),
        escapeCell(offer.company),
        `[${escapeCell(offer.title)}](${offer.url})`,
        escapeCell(offer.location || "N/A"),
        escapeCell(offer.source || "scanner"),
        escapeCell(flags || "-"),
      ]
        .join(" | ")
        .replace(/^/, "| ")
        .replace(/$/, " |")
    );
  }

  lines.push("");
  return `${lines.join("\n")}\n`;
}

function formatFit(offer) {
  return `${offer.fit} ${offer.score}%`;
}

function escapeCell(value) {
  return String(value || "")
    .replace(/\|/g, "\\|")
    .replace(/\n+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}
